config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  get 'contact_us/permalink'
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  get 'car_search/index' => 'car_search#index', :as => 'search_page'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'cars#index'
  # get 'cars/index'
  # get 'cars/show'
  # get 'manufacturers/index'
  # get 'manufacturers/show'
  # resources :home, only: %i[index]
  resources :page, except: [:show]
  get '/page/:permalink' => 'page#permalink', as: 'permalink'

  resources :cars, only: %i[index show]

  resources :cart, only: %i[create destroy index]
  resources :manufacturers, only: %i[index show]
  scope '/checkout' do
    post 'create',  to: 'checkout#create',  as: 'checkout_create'
    get  'success', to: 'checkout#success', as: 'checkout_success'
    get  'cancel',  to: 'checkout#cancel',  as: 'checkout_cancel'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  has_one_attached :image
  belongs_to :manufacturer
  has_many :order_items
  QUANTITY = %w[1 2 3 4 5 6 7 8 9 10]
  validates :model, presence: true
  validates :model, length: { minimum: 2 }
  validates :description, length: { maximum: 1000, too_long: '%{count} characters is the maximum allowed' }
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  has_many :car
  validates :name, presence: true
  validates :name, length: { minimum: 2 }
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :set_subtotal
  belongs_to :users

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  def set_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :car
  belongs_to :order
  before_save :set_unit_price
  before_save :set_total

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total
    unit_price * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total * quantity
  end
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :province
  has_many :orders
end

app/controllers/car_search_controller.rb
class CarSearchController < ApplicationController
  def index
    if params[:search].blank? && params[:category].blank? # Search and category blank
      redirect_to(root_path, alert: 'Emplty filed!') and return

    elsif params[:search].blank? && !params[:category].blank? # Search is blank
      parameter = params[:category]
      car = Manufacturer.find(parameter).car
      @result_set = car
    elsif !params[:search].blank? && params[:category].blank? # category is blank
      parameter = params[:search].downcase
      @result_set = Car.all.where('lower(model) like ?', "%#{parameter}%")
    else
      parameter = params[:search].downcase
      category = params[:category]
      car = Car.includes(:manufacturer).all.where(manufacturer: category)
      @result_set = car.where('lower(model) like ?', "%#{parameter}%")
    end
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all.page(params[:page]).per(10)
    @order_item = current_order.order_items.new
  end

  def show
    @car = Car.find(params[:id])
    add_breadcrumb 'Detailed Information', :cars_path
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def create
    #  logger.debug("Adding #{params[:id]} to cart")

    id = params[:id].to_i
    session[:shopping_cart] << id # push to an array
    car = Car.find(id)
    flash[:notice] = "➕ #{car.model} added to cart"
    redirect_to request.referrer
  end

  def destroy
    id = params[:id].to_i
    session[:shopping_cart].delete(id)
    car = Car.find(id)
    flash[:notice] = "➕ #{car.model} removed to cart"
    redirect_to request.referrer
  end

  def index
    @order_items = current_order.order_items
    @items = Car.find(session[:shopping_cart])
    @subtotal = 0
    @Gst_in_percent = current_user.province.GST
    @Pst_in_percent = current_user.province.PST
    @Hst_in_percent = current_user.province.HST
    # @abc = params[:quantitys]kr
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create
    @total = 0
    @products = Car.find(session[:shopping_cart])
    @product = @products.map do |u|
      @total += u.price
      { 'name' => u.model, 'description' => u.description, 'amount' => (u.price * 100).to_i, 'currency' => 'cad',
        'quantity' => 1 }
    end
    if @products.nil?
      redirect_to root_path
      nil
    end
    @session = Stripe::Checkout::Session.create(
      # went to stripe API, looked up sessions, figured it all out..
      payment_method_types: ['card'],
      success_url: checkout_success_url,
      cancel_url: checkout_cancel_url,
      line_items:
        @products.map do |u|
          @total += u.price
          { 'name' => u.model, 'description' => u.description, 'amount' => (u.price * 100).to_i, 'currency' => 'cad',
            'quantity' => 1 }
        end
    )
    redirect_to @session.url
  end

  def success
    redirect_to root_path
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def permalink
    @page = Page.find_by(permalink: params[:permalink])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_order
    if Order.find_by_id(session[:order_id]).nil?
      Order.new
    else
      Order.find_by_id(session[:order_id])
    end
  end
end

app/helpers/car_search_helper.rb
module CarSearchHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/car_search/index.html.erb
<% if @result_set.empty? %>
<br/><br/><h2>Nothing is found</h2><br/><br/>
<% else%>
<br/><br/><h2>Cars found are</h2><br/><br/>
<% @result_set.each do |result|%>
  <ul class="list-group">
       <li class="list-group-item ">  <%= link_to result.model, result %><br></li>
          </ul>
  <% end %>
<%end%>

app/views/cart/_cart.html.erb
<%= link_to "#{current_order.order.order_items.size} items with a value of $#{current_order.subtotal}", cart_path %>

app/views/cart/index.html.erb
<h1><%=@user %></h1>
<%if @items.count != 0 %>
<figure class="text-center m-0 h1">
  <blockquote class="blockquote">
    <p>Shopping Cart 🛒</p>
  </blockquote>
</figure>

<table class="table table-striped m-5" style="max-width: 90%;">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Price</th>
<%# <th scope="col">Quantity</th> %>
       <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
   <% @items.each do |item| %>
    <tr>
      <td scope="row"><%= item.model %></td>
      <td><%= item.description %></td>
      <td><%=  number_to_currency item.price %></td>
         <td><%=   item.quantity %></td>
      <%# <%= simple_form_for @cart, html: {multipart: true} do |f| %>
     <%# <td> <%= f.input_field :quantity collection: Car::QUANTITY, prompt: "Select quantity" %>
    <td class="btn btn-primary m-1 p-1"><%= button_to cart_path(item), method: :delete do %>
     Delete<% end %><td>
    </tr>
     <% @subtotal = @subtotal + item.price  %>
    <% end%>
  </tbody>

</table>

<table class="table table-striped m-5" style="max-width: 90%;">
  <thead>
    <tr>
      <th scope="col">Subtotal</th>
      <th scope="col">GST</th>
      <th scope="col">PST</th>
       <th scope="col">HST</th>
         <th scope="col">Total</th>
    </tr>
  </thead>
  <tbody>
   <tr>
      <td scope="row"><%=number_to_currency @subtotal %></td>
      <td><%= number_to_currency (@subtotal * @Gst_in_percent)/100 %></td>
      <td><%=  number_to_currency (@subtotal * @Pst_in_percent)/100  %></td>
      <td><%=  number_to_currency (@subtotal * @Hst_in_percent)/100  %></td>
      <td><%=number_to_currency (@subtotal * @Hst_in_percent)/100 + (@subtotal * @Gst_in_percent)/100 +(@subtotal * @Pst_in_percent)/100 + @subtotal %></td>

    </tr>
      </tbody>

</table>

<%= form_with url: checkout_create_path, remote: true do %>
      <%= hidden_field_tag(:cart, @items)%>
      <%= button_tag "Checkout" %>
<% end %>

<%# <h4 class=" text-center">The subTotal is - <span style="color:blue"><%=number_to_currency @subtotal</span></h4 %>
<%# <h4 class="text-center">The GST is - <span style="color:blue"><%=number_to_currency (@subtotal * @Gst_in_percent)/100 %></span></h4>
<%# <h4 class="text-center">The PST is - <span style="color:blue"><%=number_to_currency (@subtotal * @Pst_in_percent)/100 %></span></h4>
<%# <h4 class="text-center">The HST is - <span style="color:blue"><%=number_to_currency (@subtotal * @Hst_in_percent)/100 %></span></h4>
<%# <h4 class="text-center">The Total is - <span style="color:blue"><%=number_to_currency (@subtotal * @Hst_in_percent)/100 + (@subtotal * @Gst_in_percent)/100 +(@subtotal * @Pst_in_percent)/100 + @subtotal%></span></p>
<%else %>
    <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>

<%end%>