config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  get 'contact_us/permalink'
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  get 'car_search/index' => 'car_search#index', :as => 'search_page'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'cars#index'
  # get 'cars/index'
  # get 'cars/show'
  # get 'manufacturers/index'
  # get 'manufacturers/show'
  # resources :home, only: %i[index]
  resources :page, except: [:show]
  get '/page/:permalink' => 'page#permalink', as: 'permalink'

  resources :cars, only: %i[index show]

  resources :cart, only: %i[create destroy index]
  resources :manufacturers, only: %i[index show]
  scope '/checkout' do
    post 'create',  to: 'checkout#create',  as: 'checkout_create'
    get  'success', to: 'checkout#success', as: 'checkout_success'
    get  'cancel',  to: 'checkout#cancel',  as: 'checkout_cancel'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  has_one_attached :image
  belongs_to :manufacturer
  has_many :order_items
  QUANTITY = %w[1 2 3 4 5 6 7 8 9 10]
  validates :model, presence: true
  validates :model, length: { minimum: 2 }
  validates :description, length: { maximum: 1000, too_long: '%{count} characters is the maximum allowed' }
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  has_many :car
  validates :name, presence: true
  validates :name, length: { minimum: 2 }
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :set_subtotal
  belongs_to :users

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  def set_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :car
  belongs_to :order
  before_save :set_unit_price
  before_save :set_total

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total
    unit_price * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total * quantity
  end
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :province
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  before_action :initialize_session
  helper_method :cart
  before_action :authenticate_user!
  add_breadcrumb 'home', :root_path
  add_breadcrumb 'Cars by specific manufacturer', :manufacturers_path

  def initialize_session
    session[:shopping_cart] ||= []
  end

  def cart
    Car.find(session[:shopping_cart])
  end
end

app/controllers/car_search_controller.rb
class CarSearchController < ApplicationController
  def index
    if params[:search].blank? && params[:category].blank? # Search and category blank
      redirect_to(root_path, alert: 'Emplty filed!') and return

    elsif params[:search].blank? && !params[:category].blank? # Search is blank
      parameter = params[:category]
      car = Manufacturer.find(parameter).car
      @result_set = car
    elsif !params[:search].blank? && params[:category].blank? # category is blank
      parameter = params[:search].downcase
      @result_set = Car.all.where('lower(model) like ?', "%#{parameter}%")
    else
      parameter = params[:search].downcase
      category = params[:category]
      car = Car.includes(:manufacturer).all.where(manufacturer: category)
      @result_set = car.where('lower(model) like ?', "%#{parameter}%")
    end
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all.page(params[:page]).per(10)
    @order_item = current_order.order_items.new
  end

  def show
    @car = Car.find(params[:id])
    add_breadcrumb 'Detailed Information', :cars_path
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def create
    #  logger.debug("Adding #{params[:id]} to cart")

    id = params[:id].to_i
    session[:shopping_cart] << id # push to an array
    car = Car.find(id)
    flash[:notice] = "➕ #{car.model} added to cart"
    redirect_to request.referrer
  end

  def destroy
    id = params[:id].to_i
    session[:shopping_cart].delete(id)
    car = Car.find(id)
    flash[:notice] = "➕ #{car.model} removed to cart"
    redirect_to request.referrer
  end

  def index
    @order_items = current_order.order_items
    @items = Car.find(session[:shopping_cart])
    @subtotal = 0
    @Gst_in_percent = current_user.province.GST
    @Pst_in_percent = current_user.province.PST
    @Hst_in_percent = current_user.province.HST
    # @abc = params[:quantitys]kr
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create
    @total = 0
    @products = Car.find(session[:shopping_cart])
    @product = @products.map do |u|
      @total += u.price
      { 'name' => u.model, 'description' => u.description, 'amount' => (u.price * 100).to_i, 'currency' => 'cad',
        'quantity' => 1 }
    end
    if @products.nil?
      redirect_to root_path
      nil
    end
    @session = Stripe::Checkout::Session.create(
      # went to stripe API, looked up sessions, figured it all out..
      payment_method_types: ['card'],
      success_url: checkout_success_url,
      cancel_url: checkout_cancel_url,
      line_items:
        @products.map do |u|
          @total += u.price
          { 'name' => u.model, 'description' => u.description, 'amount' => (u.price * 100).to_i, 'currency' => 'cad',
            'quantity' => 1 }
        end
    )
    redirect_to @session.url
  end

  def success
    redirect_to root_path
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def permalink
    @page = Page.find_by(permalink: params[:permalink])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_order
    if Order.find_by_id(session[:order_id]).nil?
      Order.new
    else
      Order.find_by_id(session[:order_id])
    end
  end
end

app/helpers/car_search_helper.rb
module CarSearchHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/cars/_car.html.erb
 <div class="col-sm-3">
    <div class="card">
      <div class="card-body">
      <%= image_tag car.image , width: "200" , height: "200",alt:"Logo"%>
        <h3 class="card-title"><%= link_to car.model, car %></h3>
        <h4 class="card-text"><span style="font-weight:bold" >Made By:</span> <%=link_to car.manufacturer.name, car.manufacturer%></h4>
        <h4 class="card-text"><span style="font-weight:bold" >Feature: </span><%= car.description %></h4>
<%# <%= form_with model: car do |f|%>
<%# <%= f.number_field :quantity, value: item.quantity %>
          <%= form_with url: cart_index_path,remote: true, method: :post do |f| %>
      <%= hidden_field_tag(:id, car.id) %>
        <%= hidden_field_tag(:price, car.price) %>
         <%= f.number_field :quantitys, in: 1.0..20.0, step: 1, :value => 1  %>
   <%# <%= number_field_tag 'car[][quantity]', {}, id: "car_id" + product.id.to_s %>
        <%= button_tag 'Add to Cart' %>
        <% end %>

          <% if cart.include?(car) %>

        <%= button_to cart_path(car), method: :delete do%>
        Remove From Cart
        <% end%>


        <% end %>
      </div>
    </div>
  </div>

app/views/cars/index.html.erb
<%# # <%= debug cart %>

 <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

   <%if flash[:notice]%>
   <p><%= flash[:notice]%>
   <%end%>
    <%= link_to image_tag("cart.jpg", width:60, alt: "") ,cart_index_path%>
      <ul>
        <li>Cart <% if cart.present?%>
              <sup><%= cart.size %></sup></li>
              <% cart.each do |car|%>
            <li>
              <%= car.model%><%= link_to 'DELETE', cart_path(car), method: :delete %>
            </li>
          <%end%>
        <%end%>
 </ul>

<h1 style="color:blue;">Buy Cars, Become Lazy</h1>

<%= paginate @cars %>
<div class="row">
<% @cars.each do |car| %>
<%= render :partial => 'car', locals: { car: car } %>
  <% end %>
</div>

app/views/cars/show.html.erb
<div class="card">
  <div class="card-header"><h2><%= @car.model %></h2></div>
  <div class="card-body">
<%= render_breadcrumbs %>

  <ul>

<p id="notice"><%= notice %></p>
    <%= image_tag @car.image , width: '400', height: '400'%></span>
    <li><span style="font-weight:bold" >Feature: </span><span><%= @car.description %></span></li>
    <li><span style="font-weight:bold">Quantity: </span><span><%= @car.quantity %></span></li>
    <li><span style="font-weight:bold">License Plate: </span><span><%= number_to_currency @car.price %></span></li>
    <li><span style="font-weight:bold">Year: </span><span><%= @car.year %></span></li>
    <li><span style="font-weight:bold">Door Count: </span><span><%= @car.doorCount %></span></li>
    <li><span style="font-weight:bold">Mileage: </span><span><%= @car.mileage %></span></li>
    <li><span style="font-weight:bold">Manufacturer: </span><span><%= @car.manufacturer.name %></span></li>
  </ul>
  </div>
</div>