config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  get 'contact_us/permalink'
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  get 'car_search/index' => 'car_search#index', :as => 'search_page'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'cars#index'
  # get 'cars/index'
  # get 'cars/show'
  # get 'manufacturers/index'
  # get 'manufacturers/show'
  # resources :home, only: %i[index]
  resources :page, except: [:show]
  get '/page/:permalink' => 'page#permalink', as: 'permalink'

  resources :cars, only: %i[index show]

  resources :cart, only: %i[create destroy index]
  resources :manufacturers, only: %i[index show]
  scope '/checkout' do
    post 'create',  to: 'checkout#create',  as: 'checkout_create'
    get  'success', to: 'checkout#success', as: 'checkout_success'
    get  'cancel',  to: 'checkout#cancel',  as: 'checkout_cancel'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  has_one_attached :image
  belongs_to :manufacturer
  has_many :order_items
  QUANTITY = %w[1 2 3 4 5 6 7 8 9 10]
  validates :model, presence: true
  validates :model, length: { minimum: 2 }
  validates :description, length: { maximum: 1000, too_long: '%{count} characters is the maximum allowed' }
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  has_many :car
  validates :name, presence: true
  validates :name, length: { minimum: 2 }
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :set_subtotal
  belongs_to :users

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  def set_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :car
  belongs_to :order
  before_save :set_unit_price
  before_save :set_total

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total
    unit_price * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total * quantity
  end
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :province
  has_many :orders
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all.page(params[:page]).per(10)
    @order_item = current_order.order_items.new
  end

  def show
    @car = Car.find(params[:id])
    add_breadcrumb 'Detailed Information', :cars_path
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def create
    #  logger.debug("Adding #{params[:id]} to cart")

    id = params[:id].to_i
    session[:shopping_cart] << id # push to an array
    car = Car.find(id)
    flash[:notice] = "➕ #{car.model} added to cart"
    redirect_to request.referrer
  end

  def destroy
    id = params[:id].to_i
    session[:shopping_cart].delete(id)
    car = Car.find(id)
    flash[:notice] = "➕ #{car.model} removed to cart"
    redirect_to request.referrer
  end

  def index
    @order_items = current_order.order_items
    @items = Car.find(session[:shopping_cart])
    @subtotal = 0
    @Gst_in_percent = current_user.province.GST
    @Pst_in_percent = current_user.province.PST
    @Hst_in_percent = current_user.province.HST
    # @abc = params[:quantitys]kr
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def permalink
    @page = Page.find_by(permalink: params[:permalink])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_order
    if Order.find_by_id(session[:order_id]).nil?
      Order.new
    else
      Order.find_by_id(session[:order_id])
    end
  end
end

app/helpers/car_search_helper.rb
module CarSearchHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Cars</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

<div class="navbar-text float-right">
<% if user_signed_in? %>

  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>


<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>


<% end %>
 </div>




  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-lg">
                  <ul class="list-group list-group-horizontal">
                  <li class="list-group-item"><%= link_to "Manufacturers", manufacturers_url%></li>
                  <li class="list-group-item"><%= link_to "Cars", cars_url%></li>
                  <li class="list-group-item">  <%= link_to 'About Us', permalink_path('about_us') %></li>
                  <%# <li class="list-group-item"> <%= link_to 'Contact Us', permalink_path('contact_us') %>
                  </ul>
          <%= form_tag(search_page_path, :method => "get",
        class: 'navbar-form navbar-left') do %>
      <div class="input-group mb-3">
        <%= select_tag 'category', options_from_collection_for_select(Manufacturer.all, :id,:name), include_blank: "Manufacturer", class: "select is-info" %>
        <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
        <div class="input-group-btn">
          <%= button_tag "Search", :class => 'btn btn-dark',:name => nil%>
        </div>
      </div>


    <% end %>
    </div>
  </nav>

    <%= yield %>
<%# <footer> %>
      <%# <details>
        <summary>
            Cart
            <% if cart.present? %>
              <%# <sup><%= cart.size</sup> %>
            <%# <% end %>
        <%# </summary> %> %> %>
        <%# <% if cart.present? %> %>
          <%# <ul>
            <% cart.each do |car| %>
              <%# <li>
                <%# <%= car.model %>
                <%# <%= link_to '❌', cart_path(car), method: :delete %>  %>
              <%# </li>
            <% end %>
          <%# </ul>
        <% else %>
          <%# <p>No items in your cart.</p> %>
        <%# <% end %>
      <%# </details>
      <hr>
      <p>
    </footer> %>
  </body>
</html>

app/views/page/permalink.html.erb
<h1><%= @page.title%> </h1>
<p><%= @page.content%> <p>